-- 1. PB_USER 테이블
ALTER TABLE PB_USER DROP FOREIGN KEY PB_USER_ibfk_1;
ALTER TABLE PB_USER ADD CONSTRAINT fk_pb_user_account FOREIGN KEY (u_id) REFERENCES ACCOUNT(id) ON DELETE CASCADE;

ALTER TABLE PB_USER DROP FOREIGN KEY PB_USER_ibfk_2;
ALTER TABLE PB_USER ADD CONSTRAINT fk_pb_user_branch FOREIGN KEY (branch) REFERENCES BRANCH(b_id) ON DELETE CASCADE;

-- 2. KPI 테이블
ALTER TABLE KPI DROP FOREIGN KEY KPI_ibfk_1;
ALTER TABLE KPI ADD CONSTRAINT fk_kpi_pb FOREIGN KEY (u_id) REFERENCES PB_USER(u_id) ON DELETE CASCADE;

ALTER TABLE KPI DROP FOREIGN KEY KPI_ibfk_2;
ALTER TABLE KPI ADD CONSTRAINT fk_kpi_branch FOREIGN KEY (b_id) REFERENCES BRANCH(b_id) ON DELETE CASCADE;

-- 3. CUSTOMER_RELATIONSHIP
ALTER TABLE CUSTOMER_RELATIONSHIP DROP FOREIGN KEY CUSTOMER_RELATIONSHIP_ibfk_1;
ALTER TABLE CUSTOMER_RELATIONSHIP ADD CONSTRAINT fk_cr_customer FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE;

-- 4. CUSTOMER_INFORMATION
ALTER TABLE CUSTOMER_INFORMATION DROP FOREIGN KEY CUSTOMER_INFORMATION_ibfk_1;
ALTER TABLE CUSTOMER_INFORMATION ADD CONSTRAINT fk_ci_customer FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE;

-- 5. CUSTOMER_TRANSACTION
ALTER TABLE CUSTOMER_TRANSACTION DROP FOREIGN KEY CUSTOMER_TRANSACTION_ibfk_1;
ALTER TABLE CUSTOMER_TRANSACTION ADD CONSTRAINT fk_ct_customer FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE;

ALTER TABLE CUSTOMER_TRANSACTION DROP FOREIGN KEY CUSTOMER_TRANSACTION_ibfk_2;
ALTER TABLE CUSTOMER_TRANSACTION ADD CONSTRAINT fk_ct_account FOREIGN KEY (ca_id) REFERENCES CUSTOMER_ACCOUNT(ca_id) ON DELETE CASCADE;

-- 6. CUSTOMER_ACCOUNT
ALTER TABLE CUSTOMER_ACCOUNT DROP FOREIGN KEY CUSTOMER_ACCOUNT_ibfk_1;
ALTER TABLE CUSTOMER_ACCOUNT ADD CONSTRAINT fk_ca_customer FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE;

ALTER TABLE CUSTOMER_ACCOUNT DROP FOREIGN KEY CUSTOMER_ACCOUNT_ibfk_2;
ALTER TABLE CUSTOMER_ACCOUNT ADD CONSTRAINT fk_ca_product FOREIGN KEY (cu_id) REFERENCES CUSTOMER_PRODUCT(cu_id) ON DELETE CASCADE;

-- 7. CUSTOMER_PRODUCT
ALTER TABLE CUSTOMER_PRODUCT DROP FOREIGN KEY CUSTOMER_PRODUCT_ibfk_1;
ALTER TABLE CUSTOMER_PRODUCT ADD CONSTRAINT fk_cp_product FOREIGN KEY (pd_id) REFERENCES PRODUCT(pd_id) ON DELETE CASCADE;

ALTER TABLE CUSTOMER_PRODUCT DROP FOREIGN KEY CUSTOMER_PRODUCT_ibfk_2;
ALTER TABLE CUSTOMER_PRODUCT ADD CONSTRAINT fk_cp_customer FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE;

-- 8. IN_CHARGE
ALTER TABLE IN_CHARGE DROP FOREIGN KEY IN_CHARGE_ibfk_1;
ALTER TABLE IN_CHARGE ADD CONSTRAINT fk_incharge_pb FOREIGN KEY (u_id) REFERENCES PB_USER(u_id) ON DELETE CASCADE;

ALTER TABLE IN_CHARGE DROP FOREIGN KEY IN_CHARGE_ibfk_2;
ALTER TABLE IN_CHARGE ADD CONSTRAINT fk_incharge_customer FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE;

-- 9. CHURN_LEVEL
ALTER TABLE CHURN_LEVEL DROP FOREIGN KEY CHURN_LEVEL_ibfk_1;
ALTER TABLE CHURN_LEVEL ADD CONSTRAINT fk_churn_customer FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE;

-- 10. CONSULTATION_MEMO
ALTER TABLE CONSULTATION_MEMO DROP FOREIGN KEY CONSULTATION_MEMO_ibfk_1;
ALTER TABLE CONSULTATION_MEMO ADD CONSTRAINT fk_cm_customer FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE;

ALTER TABLE CONSULTATION_MEMO DROP FOREIGN KEY CONSULTATION_MEMO_ibfk_2;
ALTER TABLE CONSULTATION_MEMO ADD CONSTRAINT fk_cm_pb FOREIGN KEY (u_id) REFERENCES PB_USER(u_id) ON DELETE CASCADE;

-- 11. CONSULTATION_REPORT
ALTER TABLE CONSULTATION_REPORT DROP FOREIGN KEY CONSULTATION_REPORT_ibfk_1;
ALTER TABLE CONSULTATION_REPORT ADD CONSTRAINT fk_cr_memo FOREIGN KEY (cm_id) REFERENCES CONSULTATION_MEMO(cm_id) ON DELETE CASCADE;

-- 12. AI_TODO
ALTER TABLE AI_TODO DROP FOREIGN KEY AI_TODO_ibfk_1;
ALTER TABLE AI_TODO ADD CONSTRAINT fk_todo_pb FOREIGN KEY (u_id) REFERENCES PB_USER(u_id) ON DELETE CASCADE;

-- 13. SCHEDULE (현재 테이블명 유지 시)
ALTER TABLE SCHEDULE DROP FOREIGN KEY SCHEDULE_ibfk_1;
ALTER TABLE SCHEDULE ADD CONSTRAINT fk_sch_pb FOREIGN KEY (u_id) REFERENCES PB_USER(u_id) ON DELETE CASCADE;

ALTER TABLE SCHEDULE DROP FOREIGN KEY SCHEDULE_ibfk_2;
ALTER TABLE SCHEDULE ADD CONSTRAINT fk_sch_customer FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE;

ALTER TABLE SCHEDULE DROP FOREIGN KEY SCHEDULE_ibfk_3;
ALTER TABLE SCHEDULE ADD CONSTRAINT fk_sch_todo FOREIGN KEY (at_id) REFERENCES AI_TODO(at_id) ON DELETE CASCADE;

-- 14. NOTIFICATION
ALTER TABLE NOTIFICATION DROP FOREIGN KEY NOTIFICATION_ibfk_1;
ALTER TABLE NOTIFICATION ADD CONSTRAINT fk_noti_pb FOREIGN KEY (u_id) REFERENCES PB_USER(u_id) ON DELETE CASCADE;

ALTER TABLE NOTIFICATION DROP FOREIGN KEY NOTIFICATION_ibfk_2;
ALTER TABLE NOTIFICATION ADD CONSTRAINT fk_noti_sch FOREIGN KEY (s_id) REFERENCES PB_SCHEDULE(s_id) ON DELETE CASCADE;

-- 15. HANDOVER
ALTER TABLE HANDOVER DROP FOREIGN KEY HANDOVER_ibfk_1;
ALTER TABLE HANDOVER ADD CONSTRAINT fk_ho_account FOREIGN KEY (a_id) REFERENCES ACCOUNT(id) ON DELETE CASCADE;

ALTER TABLE HANDOVER DROP FOREIGN KEY HANDOVER_ibfk_2;
ALTER TABLE HANDOVER ADD CONSTRAINT fk_ho_customer FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE;

ALTER TABLE HANDOVER DROP FOREIGN KEY HANDOVER_ibfk_3;
ALTER TABLE HANDOVER ADD CONSTRAINT fk_ho_pb_from FOREIGN KEY (from_u_id) REFERENCES PB_USER(u_id) ON DELETE CASCADE;

ALTER TABLE HANDOVER DROP FOREIGN KEY HANDOVER_ibfk_4;
ALTER TABLE HANDOVER ADD CONSTRAINT fk_ho_pb_to FOREIGN KEY (to_u_id) REFERENCES PB_USER(u_id) ON DELETE CASCADE;